apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: ingress
  namespace: YOUR_APPLICATION
  annotations:
    configmanagement.gke.io/cluster-selector: "config"
spec:
  template:
    spec:
      backend:
        serviceName: YOUR_APPLICATION-mcs
        servicePort: 8080
